#server
# pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
server:
  port: 8080
  servlet:
      context-path: /
#spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pagetest?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver



#mybatis
mybatis:
 mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
    mapper-locations: classpath:/mapper/*.xml


#lOGc
logging:
  level:
    com.test.tools.springbootuntil: DEBUG